import { OnrampProvider, ProviderInfo } from './types';

// Provider metadata
export const PROVIDERS: Record<OnrampProvider, ProviderInfo> = {
  coinbase: {
    id: 'coinbase',
    displayName: 'Coinbase',
    description: 'Card, Apple Pay or bank transfer',
    websiteUrl: 'https://www.coinbase.com',
    logoUrl: 'https://www.coinbase.com/favicon.ico'
  },
  stripe: {
    id: 'stripe',
    displayName: 'Stripe',
    description: 'Card, Apple Pay or bank transfer',
    websiteUrl: 'https://www.stripe.com',
    logoUrl: 'https://www.stripe.com/favicon.ico'
  },
  transak: {
    id: 'transak',
    displayName: 'Transak',
    description: 'Card, Apple Pay or bank transfer',
    websiteUrl: 'https://www.transak.com',
    logoUrl: 'https://www.transak.com/favicon.ico'
  }
};

// Note: This function can be replaced with API call to fetch real time data
// Dictionary of countries and their available onramp providers
export const COUNTRY_PROVIDER_MAP: Record<string, OnrampProvider[]> = {
  AD: [PROVIDERS.transak.id, PROVIDERS.coinbase.id], // Andorra
  AE: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  AG: [PROVIDERS.transak.id, PROVIDERS.stripe.id],
  AL: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  AM: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  AO: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  AR: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  AT: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  AU: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  BB: [PROVIDERS.coinbase.id],
  BD: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  BE: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  BF: [PROVIDERS.coinbase.id],
  BG: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  BH: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  BJ: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  BM: [PROVIDERS.transak.id],
  BO: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  BR: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  BY: [PROVIDERS.coinbase.id],
  CA: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  CH: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  CI: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  CL: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  CM: [PROVIDERS.coinbase.id],
  CO: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  CR: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  CV: [PROVIDERS.transak.id],
  CY: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  CZ: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  DE: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  DK: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  DO: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  DZ: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  EC: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  EE: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  EG: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  ES: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  ET: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  FI: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  FR: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  GA: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  GB: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  GE: [PROVIDERS.transak.id, PROVIDERS.coinbase.id],
  GG: [PROVIDERS.coinbase.id],
  GH: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  GI: [PROVIDERS.coinbase.id],
  GR: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  GT: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  GU: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  GY: [PROVIDERS.stripe.id],
  HK: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  HR: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  HU: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  ID: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  IE: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  IL: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  IM: [PROVIDERS.coinbase.id],
  IN: [PROVIDERS.transak.id, PROVIDERS.coinbase.id],
  IS: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  IT: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  JE: [PROVIDERS.coinbase.id],
  JM: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  JP: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  KE: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  KG: [PROVIDERS.coinbase.id],
  KH: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  KR: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  KW: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  KY: [PROVIDERS.coinbase.id],
  KZ: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  LA: [PROVIDERS.stripe.id],
  LB: [PROVIDERS.coinbase.id],
  LC: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  LI: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  LK: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  LT: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  LU: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  LV: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  MA: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  MC: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  MD: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  MG: [PROVIDERS.stripe.id],
  MK: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  MN: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  MO: [PROVIDERS.stripe.id],
  MT: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  MU: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  MX: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  MY: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  MZ: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  NA: [PROVIDERS.stripe.id],
  NE: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  NG: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  NI: [PROVIDERS.coinbase.id],
  NL: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  NO: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  NP: [PROVIDERS.coinbase.id],
  NZ: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  OM: [PROVIDERS.stripe.id],
  PA: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  PE: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  PH: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  PK: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  PL: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  PT: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  PY: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  QA: [PROVIDERS.stripe.id],
  RO: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  RS: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  RW: [PROVIDERS.stripe.id],
  SA: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  SD: [PROVIDERS.coinbase.id],
  SE: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  SG: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  SI: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  SK: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  SM: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  SN: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  SV: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  TH: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  TJ: [PROVIDERS.transak.id],
  TN: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  TR: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  TT: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  TZ: [PROVIDERS.stripe.id],
  UA: [PROVIDERS.coinbase.id],
  UY: [PROVIDERS.stripe.id],
  UZ: [PROVIDERS.stripe.id],
  US: [PROVIDERS.transak.id, PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  VN: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  ZA: [PROVIDERS.coinbase.id, PROVIDERS.stripe.id],
  AX: [PROVIDERS.transak.id]
};
