import { OnrampProvider, ProviderInfo } from './types';

// Provider metadata
export const PROVIDERS: Record<OnrampProvider, ProviderInfo> = {
  coinbase: {
    id: 'coinbase',
    displayName: 'Coinbase',
    websiteUrl: 'https://www.coinbase.com'
  },
  stripe: {
    id: 'stripe',
    displayName: 'Stripe',
    websiteUrl: 'https://www.stripe.com'
  },
  transak: {
    id: 'transak',
    displayName: 'Transak',
    websiteUrl: 'https://www.transak.com'
  }
};

// Note: This function can be replaced with API call to fetch real time data
// Dictionary of countries and their available onramp providers
export const COUNTRY_PROVIDER_MAP: Record<string, OnrampProvider[]> = {
  AD: ['transak', 'coinbase'], // Andorra
  AE: ['coinbase', 'stripe'],
  AG: ['transak', 'stripe'],
  AL: ['coinbase', 'stripe'],
  AM: ['coinbase', 'stripe'],
  AO: ['coinbase', 'stripe'],
  AR: ['coinbase', 'stripe'],
  AT: ['transak', 'coinbase', 'stripe'],
  AU: ['transak', 'coinbase', 'stripe'],
  BB: ['coinbase'],
  BD: ['coinbase', 'stripe'],
  BE: ['transak', 'coinbase', 'stripe'],
  BF: ['coinbase'],
  BG: ['coinbase', 'stripe'],
  BH: ['coinbase', 'stripe'],
  BJ: ['coinbase', 'stripe'],
  BM: ['transak'],
  BO: ['coinbase', 'stripe'],
  BR: ['transak', 'coinbase', 'stripe'],
  BY: ['coinbase'],
  CA: ['transak', 'coinbase', 'stripe'],
  CH: ['transak', 'coinbase', 'stripe'],
  CI: ['coinbase', 'stripe'],
  CL: ['coinbase', 'stripe'],
  CM: ['coinbase'],
  CO: ['coinbase', 'stripe'],
  CR: ['coinbase', 'stripe'],
  CV: ['transak'],
  CY: ['transak', 'coinbase', 'stripe'],
  CZ: ['transak', 'coinbase', 'stripe'],
  DE: ['transak', 'coinbase', 'stripe'],
  DK: ['transak', 'coinbase', 'stripe'],
  DO: ['coinbase', 'stripe'],
  DZ: ['coinbase', 'stripe'],
  EC: ['coinbase', 'stripe'],
  EE: ['transak', 'coinbase', 'stripe'],
  EG: ['coinbase', 'stripe'],
  ES: ['transak', 'coinbase', 'stripe'],
  ET: ['coinbase', 'stripe'],
  FI: ['transak', 'coinbase', 'stripe'],
  FR: ['transak', 'coinbase', 'stripe'],
  GA: ['coinbase', 'stripe'],
  GB: ['transak', 'coinbase', 'stripe'],
  GE: ['transak', 'coinbase'],
  GG: ['coinbase'],
  GH: ['coinbase', 'stripe'],
  GI: ['coinbase'],
  GR: ['transak', 'coinbase', 'stripe'],
  GT: ['coinbase', 'stripe'],
  GU: ['transak', 'coinbase', 'stripe'],
  GY: ['stripe'],
  HK: ['transak', 'coinbase', 'stripe'],
  HR: ['coinbase', 'stripe'],
  HU: ['transak', 'coinbase', 'stripe'],
  ID: ['coinbase', 'stripe'],
  IE: ['transak', 'coinbase', 'stripe'],
  IL: ['transak', 'coinbase', 'stripe'],
  IM: ['coinbase'],
  IN: ['transak', 'coinbase'],
  IS: ['transak', 'coinbase', 'stripe'],
  IT: ['transak', 'coinbase', 'stripe'],
  JE: ['coinbase'],
  JM: ['coinbase', 'stripe'],
  JP: ['coinbase', 'stripe'],
  KE: ['coinbase', 'stripe'],
  KG: ['coinbase'],
  KH: ['coinbase', 'stripe'],
  KR: ['coinbase', 'stripe'],
  KW: ['transak', 'coinbase', 'stripe'],
  KY: ['coinbase'],
  KZ: ['coinbase', 'stripe'],
  LA: ['stripe'],
  LB: ['coinbase'],
  LC: ['coinbase', 'stripe'],
  LI: ['transak', 'coinbase', 'stripe'],
  LK: ['coinbase', 'stripe'],
  LT: ['transak', 'coinbase', 'stripe'],
  LU: ['transak', 'coinbase', 'stripe'],
  LV: ['transak', 'coinbase', 'stripe'],
  MA: ['coinbase', 'stripe'],
  MC: ['coinbase', 'stripe'],
  MD: ['transak', 'coinbase', 'stripe'],
  MG: ['stripe'],
  MK: ['coinbase', 'stripe'],
  MN: ['coinbase', 'stripe'],
  MO: ['stripe'],
  MT: ['transak', 'coinbase', 'stripe'],
  MU: ['transak', 'coinbase', 'stripe'],
  MX: ['transak', 'coinbase', 'stripe'],
  MY: ['transak', 'coinbase', 'stripe'],
  MZ: ['coinbase', 'stripe'],
  NA: ['stripe'],
  NE: ['coinbase', 'stripe'],
  NG: ['coinbase', 'stripe'],
  NI: ['coinbase'],
  NL: ['transak', 'coinbase', 'stripe'],
  NO: ['transak', 'coinbase', 'stripe'],
  NP: ['coinbase'],
  NZ: ['transak', 'coinbase', 'stripe'],
  OM: ['stripe'],
  PA: ['coinbase', 'stripe'],
  PE: ['transak', 'coinbase', 'stripe'],
  PH: ['transak', 'coinbase', 'stripe'],
  PK: ['coinbase', 'stripe'],
  PL: ['transak', 'coinbase', 'stripe'],
  PT: ['transak', 'coinbase', 'stripe'],
  PY: ['coinbase', 'stripe'],
  QA: ['stripe'],
  RO: ['transak', 'coinbase', 'stripe'],
  RS: ['transak', 'coinbase', 'stripe'],
  RW: ['stripe'],
  SA: ['coinbase', 'stripe'],
  SD: ['coinbase'],
  SE: ['transak', 'coinbase', 'stripe'],
  SG: ['coinbase', 'stripe'],
  SI: ['transak', 'coinbase', 'stripe'],
  SK: ['transak', 'coinbase', 'stripe'],
  SM: ['coinbase', 'stripe'],
  SN: ['coinbase', 'stripe'],
  SV: ['coinbase', 'stripe'],
  TH: ['coinbase', 'stripe'],
  TJ: ['transak'],
  TN: ['coinbase', 'stripe'],
  TR: ['coinbase', 'stripe'],
  TT: ['coinbase', 'stripe'],
  TZ: ['stripe'],
  UA: ['coinbase'],
  UY: ['stripe'],
  UZ: ['stripe'],
  US: ['transak', 'coinbase', 'stripe'],
  VN: ['coinbase', 'stripe'],
  ZA: ['coinbase', 'stripe'],
  AX: ['transak']
};
